# docker-compose.yml
version: "3.9"
services:
  web:
    container_name: starter-next-docker-development
    image: fjkun06/basic-app-dev:v1
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # live code sync
      - /app/node_modules/
    ports:
      - "3000:3000"
  
